dist: xenial
sudo: false

language: c++

# At the moment, our LCI submodule has an additional submodule within it
# that refers to some non-public copy of googletest. To avoid failing when
# cloning Galois, we have to turn off cloning submodules.
git:
  submodules: false

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      before_script:
        - export CC=clang
        - export CXX=clang++
        - brew install openmpi
        - mkdir build
        - pushd build
        - cmake -DCMAKE_BUILD_TYPE=Release -DNUM_TEST_THREADS=2 -DENABLE_DIST_GALOIS=ON .. || exit 1
    - env:
        - GCC_VER=7
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-7
            - g++-7
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=9
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=7
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=10
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=10
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=10
        # set -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR to avoid compiler errors in boost headers.
        # This comes from using a boost built with libstdc++ with libc++. None of the APIs we
        # use expose stdlib objects directly though, so the build still works in-spite of the
        # different standard libraries and this is easier than getting a libc++ build of boost.
        - CXXFLAGS="-stdlib=libc++ -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - libc++-10-dev
            - libc++abi-10-dev
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=10
        - BUILD_TYPE=Debug
        # -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR work around to avoid compiler errors
        # when using libc++ and boost together. See above.
        - CXXFLAGS="-stdlib=libc++ -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR"
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
            - libc++-10-dev
            - libc++abi-10-dev
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev

before_script:
  # Depending on whether GCC_VER or CLANG_VER is set and nonempty,
  # set CC and CXX accordingly.
  - |
    if [ -n "$GCC_VER" ]; then
      export CC="gcc-$GCC_VER"
      export CXX="g++-$GCC_VER"
    fi
  - |
    if [ -n "$CLANG_VER" ]; then
      export CC="clang-$CLANG_VER"
      export CXX="clang++-$CLANG_VER"
    fi
  - |
    # Check if BUILD_TYPE is set at all, not just whether it is empty or unset.
    # See https://stackoverflow.com/a/13864829/1935144.
    if [ -z ${BUILD_TYPE+x} ]; then
      export BUILD_TYPE=Release
    fi
  - mkdir build
  - pushd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNUM_TEST_THREADS=2 -DENABLE_DIST_GALOIS=ON .. || exit 1

script:
  - make input
  - make -j2 || exit 1
  - make test || true

notifications:
  email: false
