dist: xenial
sudo: false

language: c++

# At the moment, our LCI submodule has an additional submodule within it
# that refers to some non-public copy of googletest. To avoid failing when
# cloning Galois, we have to turn off cloning submodules.
git:
  submodules: false

matrix:
  include:
    - env:
        - GCC_VER=5
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-5
            - g++-5
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=6
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-6
            - g++-6
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=7
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-7
            - g++-7
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - GCC_VER=9
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=3.8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-3.8
            - gcc-5
            - g++-5
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=3.9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-3.9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-3.9
            - gcc-5
            - g++-5
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=4.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-4.0
            - gcc-5
            - g++-5
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=5.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-5.0
            - gcc-7
            - g++-7
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=6.0
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-6.0
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=7
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-7
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-9
            - gcc-9
            - g++-9
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
    - env:
        - CLANG_VER=8
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-8
            - gcc-8
            - g++-8
            - cmake
            - libboost-all-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev

before_script:
  # Depending on whether GCC_VER or CLANG_VER is set and nonempty,
  # set CC and CXX accordingly.
  - |
    if [ -n "$GCC_VER" ]; then
      export CC="gcc-$GCC_VER"
      export CXX="g++-$GCC_VER"
    fi
  - |
    if [ -n "$CLANG_VER" ]; then
      export CC="clang-$CLANG_VER"
      export CXX="clang++-$CLANG_VER"
    fi
  - |
    # Check if BUILD_TYPE is set at all, not just whether it is empty or unset.
    # See https://stackoverflow.com/a/13864829/1935144.
    if [ -z ${BUILD_TYPE+x} ]; then
      export BUILD_TYPE=Release
    fi
  - mkdir build
  - pushd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DNUM_TEST_THREADS=2 -DENABLE_DIST_GALOIS=ON .. || exit 1

script:
  - make input
  - make -j2 || exit 1
  - make test || true

notifications:
  email: false
