dist: bionic

language: c++

# At the moment, our LCI submodule has an additional submodule within it
# that refers to some non-public copy of googletest. To avoid failing when
# cloning Galois, we have to turn off cloning submodules.
git:
  submodules: false

matrix:
  include:
    - os: osx
      osx_image: xcode11.3
      before_script:
        - export CC=clang
        - export CXX=clang++
        - brew install openmpi llvm
        - mkdir build
        - export PATH=$PATH:/usr/local/opt/llvm/bin
        - cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DENABLE_DIST_GALOIS=ON -DGALOIS_LOW_MEM=ON || exit 1
    - env:
        - GCC_VER=7
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - gcc-7
            - g++-7
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - GCC_VER=8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - gcc-8
            - g++-8
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - GCC_VER=9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - GCC_VER=9
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - gcc-9
            - g++-9
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - CLANG_VER=7
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-7 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - clang-7
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - CLANG_VER=8
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - clang-8
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - CLANG_VER=9
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - clang-9
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - CLANG_VER=10
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - clang-10
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev
    - env:
        - CLANG_VER=10
        - BUILD_TYPE=Debug
      addons:
        apt:
          sources:
            - sourceline: 'ppa:ubuntu-toolchain-r/test'
            - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
            - sourceline: 'deb https://apt.kitware.com/ubuntu/ xenial main'
              key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
            - sourceline: 'ppa:mhier/libboost-latest'
          packages:
            - clang-10
            - cmake
            - libboost1.70-dev
            - libeigen3-dev
            - openmpi-bin
            - libopenmpi-dev
            - llvm-7-dev
            - libz-dev

before_script:
  # Depending on whether GCC_VER or CLANG_VER is set and nonempty,
  # set CC and CXX accordingly.
  - |
    if [ -n "$GCC_VER" ]; then
      export CC="gcc-$GCC_VER"
      export CXX="g++-$GCC_VER"
    fi
  - |
    if [ -n "$CLANG_VER" ]; then
      export CC="clang-$CLANG_VER"
      export CXX="clang++-$CLANG_VER"
    fi
  - |
    # Check if BUILD_TYPE is set at all, not just whether it is empty or unset.
    # See https://stackoverflow.com/a/13864829/1935144.
    if [ -z ${BUILD_TYPE+x} ]; then
      export BUILD_TYPE=Release
    fi
  - mkdir build
  # Use apt-installed llvm-7-dev rather than travis-provided one which is
  # picked up through the local clang-7 install in /usr/local/clang-7.
  - export CMAKE_PREFIX_PATH=/usr/lib/llvm-7
  # Use apt-installed cmake rather than travis-provided one
  # (/usr/local/cmake-3.12.4/bin/cmake).
  - /usr/bin/cmake -S . -B build -DCMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_DIST_GALOIS=ON -DGALOIS_LOW_MEM=ON || exit 1

script:
  - make -C build input
  - cmake --build build --parallel 2 || exit 1
  - (cd build && ctest -V --parallel 2 --label-regex quick) || exit 1

notifications:
  email: false
